networks:
  proxy-test:
    driver: bridge

secrets:
  sdk-key:
    file: ./sdk-key.txt

services:
  blue:
    image: service-app
    build:
      context: ./containers/app
    container_name: service-blue
    environment:
      CONFIG_PATH: blue.yaml
      LAUNCHDARKLY_SDK_KEY_FILE: /run/secrets/sdk-key
    ports:
      - "8081:8080"
    networks:
      - proxy-test
    restart: always
    secrets:
      - sdk-key

  green:
    image: service-app
    build:
      context: ./containers/app
    container_name: service-green
    environment:
      CONFIG_PATH: green.yaml
      LAUNCHDARKLY_SDK_KEY_FILE: /run/secrets/sdk-key
    ports:
      - "8082:8080"
    networks:
      - proxy-test
    restart: always
    secrets:
      - sdk-key

  proxy_server:
    image: service-proxy
    build:
      context: ./containers/proxy
    container_name: proxy-server
    environment:
      LAUNCHDARKLY_SDK_KEY_FILE: /run/secrets/sdk-key
    ports:
      - "8080:80"
    networks:
      - proxy-test
    restart: always
    secrets:
      - sdk-key
